# Generated by Django 5.1.6 on 2025-02-22 02:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_initial_departments"),
    ]

    operations = []
